osx_image: xcode7
language: objective-c

cache:
  - bundler
  - cocoapods

before_install:
  - brew install carthage

install:
  - bundle exec rake bootstrap 

script:
  - bundle exec rake test:unit
  - bundle exec rake test:snapshot
